language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

# script: xctool -workspace Swango.xcworkspace -scheme Swango -sdk iphonesimulator

branches:
  only:
    - master
    - development
    - /^release/
