language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script: xcodebuild -workspace Swango.xcworkspace -scheme Swango -sdk iphonesimulator

cache:
  - cocoapods

branches:
  only:
    - master
    - development
    - /^release/
