language: objective-c
osx_image: xcode7.2
xcode_project: Swango.xcodeproj
xcode_scheme: Swango
xcode_sdk: iphonesimulator9.2

rvm: 2.2.2
install:
    - bundle install
    - bundle exec pod install
branches:
  only:
    - master
    - development
    - /^release/
